name: MilchserverKernPlugin
version: 0.1
description: Das Milchserver Kern Plugin
author: MysteryMine_LP
website: http://mysterymine-lp.jimdo.com/

main: org.mysterymine_lp.milchserverkernplugin.MilchserverKernPlugin

commands: 
  ping:
    description:  Schreibt Pong! zurück.
    usage:  /<command>
  heilen:
    description:  Heilt dich!
    usage:  /<command>
